### ISSUE TITLE
huawei 畅想5打不开浮悬按钮

### ISSUE THREAD

**Issue by fishsoft** [czy1121/settingscompat#1]

**Comment by czy1121** [comment]
什么系统版本？是能检测出未授权，没跳转到权限设置页吗？

**Comment by fishsoft** [comment]
没有，系统是5.1的

**Comment by czy1121** [comment]
@fishsoft 已修复，再试试

**Comment by fishsoft** [comment]
还是不能打开

**Comment by czy1121** [comment]
不能打开？希望能提供更多信息
有没有闪退？还是点了没反应？
有没有看Logcat日志？

运行新版本的demo，看看ROM版本呢

`adb pull /system/build.prop` 也可以看到ROM版本(`ro.build.version.emui`)
`adb pull /system/app/HwSystemManager.apk` 获取华为安全中心apk

**Comment by czy1121** [comment]
@fishsoft 
我在百度云真机上测过 `华为 畅享5S/5.1/emui 3.0` 没问题

**Comment by czy1121** [comment]
建议看看你的设备上是否有华为安全中心，需要在华为安全中心才能跳转，一般官方ROM上都应该有的，有些定制ROM可能没有
