### ISSUE TITLE
[疑问] 作者是怎么确定跳转时候的参数的呢？

### ISSUE THREAD

**Issue by ksxkq** [czy1121/settingscompat#5]
比如跳转的时候，intent 需要在 某个字段加上包名：
`      Intent intent = new Intent("com.meizu.safe.security.SHOW_APPSEC");
        intent.setClassName("com.meizu.safe", "com.meizu.safe.security.AppSecActivity");
        intent.putExtra("packageName", context.getPackageName());`
直接通过 log 看的吗？我自己过滤 activitymananger 日志的时候，只看到有写 (has extras)，并没有具体的值。

**Comment by czy1121** [comment]
meizu这个是从网上搜来的，网上找不到就只有获取apk反编译看源码了

悬浮窗管理一般在ROM自带的 安全中心 或 权限管理 中
对应的apk一般在 `/system/app`里
通过 `adb pull path/to/file`获取apk 
然后反编译查看源码

如果缺少设备可以通过 http://www.romzj.com/ 下载特定厂商的rom
